# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Jul  3 23:50:19 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(955, 685)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/basic-ui/icons/111267-basic-ui/svg/eye-close-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        Main.setToolTip("")
        Main.setDocumentMode(False)
        self.mainWindowContents = QtGui.QWidget(Main)
        self.mainWindowContents.setObjectName("mainWindowContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.mainWindowContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputWidget = QtGui.QWidget(self.mainWindowContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputWidget.sizePolicy().hasHeightForWidth())
        self.inputWidget.setSizePolicy(sizePolicy)
        self.inputWidget.setObjectName("inputWidget")
        self.gridLayout = QtGui.QGridLayout(self.inputWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.sourcePresetsLabel = QtGui.QLabel(self.inputWidget)
        self.sourcePresetsLabel.setObjectName("sourcePresetsLabel")
        self.gridLayout.addWidget(self.sourcePresetsLabel, 0, 0, 1, 1)
        self.outputLabel = QtGui.QLabel(self.inputWidget)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout.addWidget(self.outputLabel, 5, 0, 1, 1)
        self.deleteRawLabel = QtGui.QLabel(self.inputWidget)
        self.deleteRawLabel.setObjectName("deleteRawLabel")
        self.gridLayout.addWidget(self.deleteRawLabel, 3, 5, 1, 1)
        self.sourceFolderLabel = QtGui.QLabel(self.inputWidget)
        self.sourceFolderLabel.setObjectName("sourceFolderLabel")
        self.gridLayout.addWidget(self.sourceFolderLabel, 1, 0, 1, 1)
        self.pictureSelectLabel = QtGui.QLabel(self.inputWidget)
        self.pictureSelectLabel.setObjectName("pictureSelectLabel")
        self.gridLayout.addWidget(self.pictureSelectLabel, 3, 0, 1, 1)
        self.deleteRawCheckBox = QtGui.QCheckBox(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteRawCheckBox.sizePolicy().hasHeightForWidth())
        self.deleteRawCheckBox.setSizePolicy(sizePolicy)
        self.deleteRawCheckBox.setText("")
        self.deleteRawCheckBox.setIconSize(QtCore.QSize(24, 24))
        self.deleteRawCheckBox.setChecked(True)
        self.deleteRawCheckBox.setObjectName("deleteRawCheckBox")
        self.gridLayout.addWidget(self.deleteRawCheckBox, 3, 6, 1, 1)
        self.fileExtLineEdit = QtGui.QLineEdit(self.inputWidget)
        self.fileExtLineEdit.setStyleSheet("QLineEdit {\n"
"border: 1px solid rgb(0,0,0);\n"
"border-radius: 4px;\n"
"background-color: rgb(229, 229, 229)\n"
"}")
        self.fileExtLineEdit.setReadOnly(True)
        self.fileExtLineEdit.setObjectName("fileExtLineEdit")
        self.gridLayout.addWidget(self.fileExtLineEdit, 0, 4, 1, 3)
        self.fileExtLabel = QtGui.QLabel(self.inputWidget)
        self.fileExtLabel.setObjectName("fileExtLabel")
        self.gridLayout.addWidget(self.fileExtLabel, 0, 3, 1, 1)
        self.nFramesLabel = QtGui.QLabel(self.inputWidget)
        self.nFramesLabel.setObjectName("nFramesLabel")
        self.gridLayout.addWidget(self.nFramesLabel, 3, 3, 1, 1)
        self.line_2 = QtGui.QFrame(self.inputWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 7)
        self.nFramesSpinBox = QtGui.QSpinBox(self.inputWidget)
        self.nFramesSpinBox.setMinimum(-1)
        self.nFramesSpinBox.setObjectName("nFramesSpinBox")
        self.gridLayout.addWidget(self.nFramesSpinBox, 3, 4, 1, 1)
        self.sourcePresetsComboBox = QtGui.QComboBox(self.inputWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourcePresetsComboBox.sizePolicy().hasHeightForWidth())
        self.sourcePresetsComboBox.setSizePolicy(sizePolicy)
        self.sourcePresetsComboBox.setObjectName("sourcePresetsComboBox")
        self.gridLayout.addWidget(self.sourcePresetsComboBox, 0, 1, 1, 2)
        self.sourceFolderLineEdit = QtGui.QLineEdit(self.inputWidget)
        self.sourceFolderLineEdit.setObjectName("sourceFolderLineEdit")
        self.gridLayout.addWidget(self.sourceFolderLineEdit, 1, 1, 1, 6)
        self.pictureSelectComboBox = QtGui.QComboBox(self.inputWidget)
        self.pictureSelectComboBox.setObjectName("pictureSelectComboBox")
        self.gridLayout.addWidget(self.pictureSelectComboBox, 3, 1, 1, 2)
        self.outputLineEdit = QtGui.QLineEdit(self.inputWidget)
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.gridLayout.addWidget(self.outputLineEdit, 5, 2, 1, 5)
        self.outFolderPushButton = QtGui.QPushButton(self.inputWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon-folder-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.outFolderPushButton.setIcon(icon1)
        self.outFolderPushButton.setObjectName("outFolderPushButton")
        self.gridLayout.addWidget(self.outFolderPushButton, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.inputWidget)
        self.line = QtGui.QFrame(self.mainWindowContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.imageView = ImageView(self.mainWindowContents)
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        Main.setCentralWidget(self.mainWindowContents)
        self.menuBar = QtGui.QMenuBar(Main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 955, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPlot = QtGui.QMenu(self.menuBar)
        self.menuPlot.setObjectName("menuPlot")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(Main)
        self.toolBar.setObjectName("toolBar")
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(Main)
        self.statusBar.setObjectName("statusBar")
        Main.setStatusBar(self.statusBar)
        self.actionHome = QtGui.QAction(Main)
        self.actionHome.setObjectName("actionHome")
        self.actionRefresh = QtGui.QAction(Main)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionInfo = QtGui.QAction(Main)
        self.actionInfo.setObjectName("actionInfo")
        self.menuFile.addAction(self.actionHome)
        self.menuPlot.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionInfo)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionRefresh)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        Main.setWindowTitle(QtGui.QApplication.translate("Main", "ELENA", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcePresetsLabel.setText(QtGui.QApplication.translate("Main", "Source presets", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLabel.setText(QtGui.QApplication.translate("Main", "Output file", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRawLabel.setText(QtGui.QApplication.translate("Main", "Delete RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceFolderLabel.setText(QtGui.QApplication.translate("Main", "Source folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pictureSelectLabel.setText(QtGui.QApplication.translate("Main", "Picture select", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExtLabel.setText(QtGui.QApplication.translate("Main", "file ext", None, QtGui.QApplication.UnicodeUTF8))
        self.nFramesLabel.setText(QtGui.QApplication.translate("Main", "N frames", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlot.setTitle(QtGui.QApplication.translate("Main", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Main", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Main", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("Main", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("Main", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setShortcut(QtGui.QApplication.translate("Main", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("Main", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setShortcut(QtGui.QApplication.translate("Main", "F11", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import ImageView
from . import resources_rc
