# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Jul  4 11:14:08 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.counterSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.counterSpinBox.setStyleSheet("QSpinBox{background: none}")
        self.counterSpinBox.setFrame(False)
        self.counterSpinBox.setReadOnly(True)
        self.counterSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.counterSpinBox.setMinimum(-1)
        self.counterSpinBox.setObjectName("counterSpinBox")
        self.gridLayout.addWidget(self.counterSpinBox, 0, 6, 1, 1)
        self.saveRawLabel = QtGui.QLabel(self.centralwidget)
        self.saveRawLabel.setObjectName("saveRawLabel")
        self.gridLayout.addWidget(self.saveRawLabel, 2, 5, 1, 1)
        self.saveToLabel = QtGui.QLabel(self.centralwidget)
        self.saveToLabel.setObjectName("saveToLabel")
        self.gridLayout.addWidget(self.saveToLabel, 2, 0, 1, 1)
        self.saveToPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveToPushButton.sizePolicy().hasHeightForWidth())
        self.saveToPushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon-folder-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveToPushButton.setIcon(icon)
        self.saveToPushButton.setObjectName("saveToPushButton")
        self.gridLayout.addWidget(self.saveToPushButton, 2, 1, 1, 1)
        self.counterLabel = QtGui.QLabel(self.centralwidget)
        self.counterLabel.setObjectName("counterLabel")
        self.gridLayout.addWidget(self.counterLabel, 0, 5, 1, 1)
        self.pictureSelectComboBox = QtGui.QComboBox(self.centralwidget)
        self.pictureSelectComboBox.setObjectName("pictureSelectComboBox")
        self.gridLayout.addWidget(self.pictureSelectComboBox, 0, 1, 1, 2)
        self.nFramesSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.nFramesSpinBox.setMinimum(-1)
        self.nFramesSpinBox.setObjectName("nFramesSpinBox")
        self.gridLayout.addWidget(self.nFramesSpinBox, 0, 4, 1, 1)
        self.saveRawCheckBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawCheckBox.sizePolicy().hasHeightForWidth())
        self.saveRawCheckBox.setSizePolicy(sizePolicy)
        self.saveRawCheckBox.setText("")
        self.saveRawCheckBox.setIconSize(QtCore.QSize(24, 24))
        self.saveRawCheckBox.setChecked(True)
        self.saveRawCheckBox.setObjectName("saveRawCheckBox")
        self.gridLayout.addWidget(self.saveRawCheckBox, 2, 6, 1, 1)
        self.pictureSelectLabel = QtGui.QLabel(self.centralwidget)
        self.pictureSelectLabel.setObjectName("pictureSelectLabel")
        self.gridLayout.addWidget(self.pictureSelectLabel, 0, 0, 1, 1)
        self.saveToLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.saveToLineEdit.setObjectName("saveToLineEdit")
        self.gridLayout.addWidget(self.saveToLineEdit, 2, 2, 1, 3)
        self.nFramesLabel = QtGui.QLabel(self.centralwidget)
        self.nFramesLabel.setObjectName("nFramesLabel")
        self.gridLayout.addWidget(self.nFramesLabel, 0, 3, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.imageView = ImageView(self.centralwidget)
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyCAM", None, QtGui.QApplication.UnicodeUTF8))
        self.saveRawLabel.setText(QtGui.QApplication.translate("MainWindow", "Save RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToLabel.setText(QtGui.QApplication.translate("MainWindow", "Save to:", None, QtGui.QApplication.UnicodeUTF8))
        self.counterLabel.setText(QtGui.QApplication.translate("MainWindow", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.pictureSelectLabel.setText(QtGui.QApplication.translate("MainWindow", "Picture select", None, QtGui.QApplication.UnicodeUTF8))
        self.nFramesLabel.setText(QtGui.QApplication.translate("MainWindow", "N frames", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import ImageView
from . import resources_rc
