# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Apr 18 11:51:50 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 542)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon-eye-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bgMatchCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.bgMatchCheckBox.setObjectName("bgMatchCheckBox")
        self.gridLayout.addWidget(self.bgMatchCheckBox, 2, 0, 1, 2)
        self.saveRawLabel = QtGui.QLabel(self.centralwidget)
        self.saveRawLabel.setObjectName("saveRawLabel")
        self.gridLayout.addWidget(self.saveRawLabel, 3, 6, 1, 1)
        self.saveToLabel = QtGui.QLabel(self.centralwidget)
        self.saveToLabel.setObjectName("saveToLabel")
        self.gridLayout.addWidget(self.saveToLabel, 3, 0, 1, 1)
        self.saveToPushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveToPushButton.sizePolicy().hasHeightForWidth())
        self.saveToPushButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon-folder-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveToPushButton.setIcon(icon1)
        self.saveToPushButton.setObjectName("saveToPushButton")
        self.gridLayout.addWidget(self.saveToPushButton, 3, 1, 1, 1)
        self.counterLabel = QtGui.QLabel(self.centralwidget)
        self.counterLabel.setObjectName("counterLabel")
        self.gridLayout.addWidget(self.counterLabel, 0, 6, 1, 1)
        self.pictureSelectComboBox = QtGui.QComboBox(self.centralwidget)
        self.pictureSelectComboBox.setObjectName("pictureSelectComboBox")
        self.gridLayout.addWidget(self.pictureSelectComboBox, 0, 1, 1, 3)
        self.nFramesSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.nFramesSpinBox.setMinimum(-1)
        self.nFramesSpinBox.setMaximum(9999)
        self.nFramesSpinBox.setObjectName("nFramesSpinBox")
        self.gridLayout.addWidget(self.nFramesSpinBox, 0, 5, 1, 1)
        self.saveRawCheckBox = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveRawCheckBox.sizePolicy().hasHeightForWidth())
        self.saveRawCheckBox.setSizePolicy(sizePolicy)
        self.saveRawCheckBox.setText("")
        self.saveRawCheckBox.setIconSize(QtCore.QSize(24, 24))
        self.saveRawCheckBox.setChecked(True)
        self.saveRawCheckBox.setObjectName("saveRawCheckBox")
        self.gridLayout.addWidget(self.saveRawCheckBox, 3, 7, 1, 1)
        self.pictureSelectLabel = QtGui.QLabel(self.centralwidget)
        self.pictureSelectLabel.setObjectName("pictureSelectLabel")
        self.gridLayout.addWidget(self.pictureSelectLabel, 0, 0, 1, 1)
        self.nFramesLabel = QtGui.QLabel(self.centralwidget)
        self.nFramesLabel.setObjectName("nFramesLabel")
        self.gridLayout.addWidget(self.nFramesLabel, 0, 4, 1, 1)
        self.counterDisplay = QtGui.QLCDNumber(self.centralwidget)
        self.counterDisplay.setObjectName("counterDisplay")
        self.gridLayout.addWidget(self.counterDisplay, 0, 7, 1, 1)
        self.bgNameGuiLabel = QtGui.QLabel(self.centralwidget)
        self.bgNameGuiLabel.setObjectName("bgNameGuiLabel")
        self.gridLayout.addWidget(self.bgNameGuiLabel, 2, 2, 1, 1)
        self.bgNameLabel = QtGui.QLabel(self.centralwidget)
        self.bgNameLabel.setText("")
        self.bgNameLabel.setObjectName("bgNameLabel")
        self.gridLayout.addWidget(self.bgNameLabel, 2, 3, 1, 1)
        self.bgAcquirePushButton = QtGui.QPushButton(self.centralwidget)
        self.bgAcquirePushButton.setCheckable(True)
        self.bgAcquirePushButton.setChecked(False)
        self.bgAcquirePushButton.setObjectName("bgAcquirePushButton")
        self.gridLayout.addWidget(self.bgAcquirePushButton, 2, 5, 1, 1)
        self.bgLoadPushButton = QtGui.QPushButton(self.centralwidget)
        self.bgLoadPushButton.setObjectName("bgLoadPushButton")
        self.gridLayout.addWidget(self.bgLoadPushButton, 2, 4, 1, 1)
        self.saveToLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.saveToLineEdit.setObjectName("saveToLineEdit")
        self.gridLayout.addWidget(self.saveToLineEdit, 3, 3, 1, 3)
        self.saveNameComboBox = QtGui.QComboBox(self.centralwidget)
        self.saveNameComboBox.setObjectName("saveNameComboBox")
        self.gridLayout.addWidget(self.saveNameComboBox, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.roiControlLabel = QtGui.QLabel(self.centralwidget)
        self.roiControlLabel.setObjectName("roiControlLabel")
        self.verticalLayout_2.addWidget(self.roiControlLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.roiLeftLabel = QtGui.QLabel(self.centralwidget)
        self.roiLeftLabel.setObjectName("roiLeftLabel")
        self.horizontalLayout.addWidget(self.roiLeftLabel)
        self.roiLeftSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.roiLeftSpinBox.setObjectName("roiLeftSpinBox")
        self.horizontalLayout.addWidget(self.roiLeftSpinBox)
        self.roiWidthLabel = QtGui.QLabel(self.centralwidget)
        self.roiWidthLabel.setObjectName("roiWidthLabel")
        self.horizontalLayout.addWidget(self.roiWidthLabel)
        self.roiWidthSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.roiWidthSpinBox.setObjectName("roiWidthSpinBox")
        self.horizontalLayout.addWidget(self.roiWidthSpinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.roiMaxPushButton = QtGui.QPushButton(self.centralwidget)
        self.roiMaxPushButton.setObjectName("roiMaxPushButton")
        self.horizontalLayout.addWidget(self.roiMaxPushButton)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.roiTopLabel = QtGui.QLabel(self.centralwidget)
        self.roiTopLabel.setObjectName("roiTopLabel")
        self.verticalLayout.addWidget(self.roiTopLabel)
        self.roiTopSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.roiTopSpinBox.setObjectName("roiTopSpinBox")
        self.verticalLayout.addWidget(self.roiTopSpinBox)
        self.roiHeightLabel = QtGui.QLabel(self.centralwidget)
        self.roiHeightLabel.setObjectName("roiHeightLabel")
        self.verticalLayout.addWidget(self.roiHeightLabel)
        self.roiHeightSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.roiHeightSpinBox.setObjectName("roiHeightSpinBox")
        self.verticalLayout.addWidget(self.roiHeightSpinBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.imageView = ImageView(self.centralwidget)
        self.imageView.setObjectName("imageView")
        self.horizontalLayout_2.addWidget(self.imageView)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyCAM", None, QtGui.QApplication.UnicodeUTF8))
        self.bgMatchCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Background Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.saveRawLabel.setText(QtGui.QApplication.translate("MainWindow", "Save RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.saveToLabel.setText(QtGui.QApplication.translate("MainWindow", "Save to:", None, QtGui.QApplication.UnicodeUTF8))
        self.counterLabel.setText(QtGui.QApplication.translate("MainWindow", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.pictureSelectLabel.setText(QtGui.QApplication.translate("MainWindow", "Picture select", None, QtGui.QApplication.UnicodeUTF8))
        self.nFramesLabel.setText(QtGui.QApplication.translate("MainWindow", "N frames", None, QtGui.QApplication.UnicodeUTF8))
        self.bgNameGuiLabel.setText(QtGui.QApplication.translate("MainWindow", "Current:", None, QtGui.QApplication.UnicodeUTF8))
        self.bgAcquirePushButton.setText(QtGui.QApplication.translate("MainWindow", "Acquire", None, QtGui.QApplication.UnicodeUTF8))
        self.bgLoadPushButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.roiControlLabel.setText(QtGui.QApplication.translate("MainWindow", "ROI control:", None, QtGui.QApplication.UnicodeUTF8))
        self.roiLeftLabel.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.roiWidthLabel.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.roiMaxPushButton.setText(QtGui.QApplication.translate("MainWindow", "MAX Roi", None, QtGui.QApplication.UnicodeUTF8))
        self.roiTopLabel.setText(QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.roiHeightLabel.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import ImageView
from . import resources_rc
